-- CreateEnum
CREATE TYPE "Department" AS ENUM ('COMPUTER_ENGINEERING', 'ELECTRICAL_ENGINEERING', 'CIVIL_ENGINEERING', 'MECHANICAL_ENGINEERING', 'CHEMICAL_ENGINEERING', 'PHYSIOTHERAPY', 'PHARMACY', 'MICROBIOLOGY', 'AGRICULTURE', 'BIOTECHNOLOGY', 'CHEMISTRY', 'PHYSICS', 'MATHEMATICS', 'BUSINESS_ADMINISTRATION', 'LAW', 'COMMERCE', 'COMPUTER_APPLICATION', 'INFORMATION_TECHNOLOGY', 'ARTS', 'ENGLISH', 'HISTORY', 'SPORTS', 'PHYSICAL_EDUCATION', 'OTHER');

-- AlterTable
ALTER TABLE "event_analytics" ALTER COLUMN "completedAt" DROP NOT NULL;

-- AlterTable
ALTER TABLE "events" ADD COLUMN     "agenda" JSONB,
ADD COLUMN     "department" "Department" NOT NULL DEFAULT 'COMPUTER_ENGINEERING',
ADD COLUMN     "faqs" JSONB,
ADD COLUMN     "highlights" JSONB,
ADD COLUMN     "prizes" JSONB,
ADD COLUMN     "requirements" JSONB,
ADD COLUMN     "rules" JSONB,
ADD COLUMN     "speakers" JSONB;
